services:
  server:
    build: .
    container_name: network_project_server
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=${PORT:-3000}
